engine: LLAMACPP
generation:
  max_new_tokens: 4096
  temperature: 0.01
  top_p: 0.01
model:
  model_kwargs:
    filename: DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf
  model_max_length: 8192
  model_name: unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF
  tokenizer_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  torch_dtype_str: float16
  trust_remote_code: true
