engine: LLAMACPP
generation:
  max_new_tokens: 2048
  temperature: 0.0
  top_p: 0.9
model:
  model_kwargs:
    filename: QwQ-32B-UD-Q4_K_XL.gguf
  model_max_length: 4096
  model_name: unsloth/QwQ-32B-GGUF
  tokenizer_name: Qwen/QwQ-32B-Preview
  torch_dtype_str: float16
  trust_remote_code: true
